### ISSUE TITLE
table header with link is ugly

### ISSUE THREAD

**Issue by CyrusYip** [CyrusYip/cyrusyip-blog#7]
https://cyrusyip.org/zh-cn/post/2022/11/22/cache-rss-with-cloudflare/

![image](https://user-images.githubusercontent.com/60951091/232326558-8c3bc28f-b84f-4f54-adaa-4d821a5a56ba.png)

**Comment by Sinofine** [comment]
```css
.post .post-content>table th a {
    color: white;
}
```
you can modify the stylesheet like this.
