### ISSUE TITLE
lastmod is wrong on Vercel and Cloudflare Pages

### ISSUE THREAD

**Issue by CyrusYip** [CyrusYip/cyrusyip-blog#8]
https://cyrusyip.org/en/post/2023/01/11/fix-jellyfin-permission/

https://github.com/CyrusYip/cyrusyip-blog/commit/aaffd86505c102e5ed5d75cfac8317f3d61c5ea4

vercel:

![image](https://github.com/CyrusYip/cyrusyip-blog/assets/60951091/8a2c16fa-4276-4415-9546-ffeaa7129aeb)

cloudflare pages:

![image](https://github.com/CyrusYip/cyrusyip-blog/assets/60951091/c89e11a8-f5c7-4ae3-b68f-1b9090be1694)

local:

![image](https://github.com/CyrusYip/cyrusyip-blog/assets/60951091/86befa52-8e95-456b-abf8-ee21e0d41be1)

**Comment by CyrusYip** [comment]
> On the site host, your repository must be “deep-cloned,” so the returned .GitInfo data will be accurate. Otherwise, your site may display only data from your latest commit.
>
> https://gohugo.io/variables/git/#hosting-considerations

> When you make a [deployment](https://vercel.com/docs/deployments/overview), Vercel builds your project. During this time, Vercel performs a "shallow clone" on your Git repository using the command git clone --depth=10 (...) and fetches ten levels of git commit history. This means that only the latest ten commits are pulled and not the entire repository history.
>
> https://vercel.com/docs/deployments/configure-a-build

**Comment by CyrusYip** [comment]
I will probably migrate to Cloudflare Pages.

Todo:

- [x] convert redirection rules (https://developers.cloudflare.com/pages/platform/redirects/ , https://github.com/CyrusYip/cyrusyip-blog/blob/557dc09b0e7dadfdbb0754e04534361b65e931a6/vercel.json )
- [x] write examples for redirections

comment:

```yaml
{
  "redirects": [
    {
      "source": "/post/(index.xml)",
      "destination": "/zh-cn/$1"
      # /post/index.xml -> /zh-cn/index.xml
      # 应该是 /zh-cn/post/index.xml 才对，但 /zh-cn/post/index.xml 没有全文，/zh-cn/index.xml 有全文，将错就错还是改正呢？
      # 是不是还要加上 index.xml -> /zh-cn/index.xml ？
    },
    {
      "source": "/(about|subscribe|donate)(/?)",
      "destination": "/zh-cn/$1$2"
      # /about -> /zh-cn/about
    },
    {
      "source": "(/post/[0-9].*)",
      "destination": "/zh-cn$1"
      # /post/2020/10/02/ubuntu-compile-goldendict/ -> /zh-cn/post/2020/10/02/ubuntu-compile-goldendict/
      # 只判断了前面的日期数字，偷懒之举
    }
  ]
}
```
